// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnarJ5IKAxnObBbA7IcPn1N6KXscWxzUg',
    appId: '1:26836136800:web:fa71037c38723c5f7aa405',
    messagingSenderId: '26836136800',
    projectId: 'jambu-100d1',
    authDomain: 'jambu-100d1.firebaseapp.com',
    storageBucket: 'jambu-100d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjbvDfiio5Gc7Dy_bFIBbRa28p5mbLKv8',
    appId: '1:26836136800:android:a43c9659f8a6bf617aa405',
    messagingSenderId: '26836136800',
    projectId: 'jambu-100d1',
    storageBucket: 'jambu-100d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXA7YSNfr8wWElIOhpyAcnbd5P7Q1Uu_A',
    appId: '1:26836136800:ios:07f2000907c583cb7aa405',
    messagingSenderId: '26836136800',
    projectId: 'jambu-100d1',
    storageBucket: 'jambu-100d1.appspot.com',
    iosClientId:
        '26836136800-bsa17vo3m9mqu1h9kk44komq9igaqi9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.jambu',
  );
}
